application: obomb-web
version: 1
runtime: python
api_version: 1

handlers:
- url: /login/google
  script: login/google.py
- url: /login/mixi
  script: login/mixi.py
- url: /login/twitter
  script: login/twitter.py
- url: /login/yahoojapan
  script: login/yahoojapan.py
- url: /logout
  script: logout.py
- url: /clear
  script: clear.py
- url: /html
  static_dir: html
- url: /css
  static_dir: css
- url: /.*
  script: asklogin.py
